name: Deploy static site to S3

on:
  push:
    branches: ["main"]
    paths:
      - "site/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Who am I (STS)
        run: aws sts get-caller-identity

      - name: Show Region & Bucket
        run: |
          echo "Region: ${{ secrets.AWS_REGION }}"
          echo "Bucket: ${{ secrets.S3_BUCKET }}"

      - name: List bucket (sanity check)
        continue-on-error: true
        run: aws s3 ls s3://${{ secrets.S3_BUCKET }}

      - name: Sync site/ to S3
        run: aws s3 sync ./site s3://${{ secrets.S3_BUCKET }} --delete
